# Generated by Django 5.0.6 on 2025-12-29 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('multitenancy', '0007_tenantmembership_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField()),
                (
                    'tenant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='school_classes',
                        to='multitenancy.tenant',
                    ),
                ),
            ],
            options={
                'ordering': ('order',),
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                (
                    'school_class',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.schoolclass'
                    ),
                ),
                (
                    'tenant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='multitenancy.tenant'
                    ),
                ),
            ],
            options={
                'unique_together': {('school_class', 'name')},
            },
        ),
    ]
