# Generated by Django 5.0.6 on 2026-01-09 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('multitenancy', '0003_alter_tenantmembership_invitee_email_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                (
                    'tenant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='academic_years',
                        to='multitenancy.tenant',
                    ),
                ),
            ],
            options={
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField()),
                (
                    'academic_year',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academics.academicyear'
                    ),
                ),
                (
                    'tenant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='school_classes',
                        to='multitenancy.tenant',
                    ),
                ),
            ],
            options={
                'ordering': ('order',),
                'unique_together': {('tenant', 'academic_year', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                (
                    'school_class',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.schoolclass'
                    ),
                ),
                (
                    'tenant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='multitenancy.tenant'
                    ),
                ),
            ],
            options={
                'unique_together': {('school_class', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20)),
                (
                    'tenant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='multitenancy.tenant'
                    ),
                ),
            ],
            options={
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SectionSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'section',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='section_subjects',
                        to='academics.section',
                    ),
                ),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
            ],
            options={
                'unique_together': {('section', 'subject')},
            },
        ),
    ]
