# Generated by Django 5.0.6 on 2025-12-29 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('academics', '0001_initial'),
        ('multitenancy', '0007_tenantmembership_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('board', models.CharField(blank=True, max_length=100)),
                ('medium', models.CharField(blank=True, max_length=50)),
                ('established_year', models.PositiveIntegerField(blank=True, null=True)),
                (
                    'tenant',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name='school', to='multitenancy.tenant'
                    ),
                ),
            ],
        ),
    ]
