# Generated by Django 5.0.6 on 2026-01-09 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('academics', '0002_teacher_student_teachingassignment'),
        ('multitenancy', '0003_alter_tenantmembership_invitee_email_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_published', models.BooleanField(default=False)),
                (
                    'academic_year',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.academicyear'
                    ),
                ),
                (
                    'tenant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='multitenancy.tenant'
                    ),
                ),
            ],
            options={
                'unique_together': {('tenant', 'academic_year', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ExamSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_marks', models.PositiveIntegerField()),
                ('pass_marks', models.PositiveIntegerField()),
                (
                    'exam',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='exam_subjects', to='academics.exam'
                    ),
                ),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
            ],
            options={
                'unique_together': {('exam', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='StudentExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_absent', models.BooleanField(default=False)),
                (
                    'exam',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='student_entries', to='academics.exam'
                    ),
                ),
                (
                    'student',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='exam_entries', to='academics.student'
                    ),
                ),
            ],
            options={
                'unique_together': {('student', 'exam')},
            },
        ),
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.FloatField(blank=True, null=True)),
                (
                    'exam_subject',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.examsubject'),
                ),
                (
                    'student_exam',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='academics.studentexam'
                    ),
                ),
            ],
            options={
                'unique_together': {('student_exam', 'exam_subject')},
            },
        ),
    ]
