# Generated by Django 5.0.6 on 2026-01-09 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('academics', '0003_exam_examsubject_studentexam_studentmark'),
        ('multitenancy', '0003_alter_tenantmembership_invitee_email_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_percentage', models.FloatField()),
                ('grade', models.CharField(max_length=5)),
                (
                    'tenant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='grading_rules',
                        to='multitenancy.tenant',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.FloatField()),
                ('max_marks', models.FloatField()),
                ('percentage', models.FloatField()),
                ('is_pass', models.BooleanField()),
                ('generated_at', models.DateTimeField(auto_now=True)),
                (
                    'student_exam',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name='result', to='academics.studentexam'
                    ),
                ),
            ],
        ),
    ]
