# Generated by Django 5.0.6 on 2026-02-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0003_exam_examsubject_studentexam_studentmark"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="parent_contact",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
