# Generated by Django 5.0.6 on 2026-01-10 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('academics', '0004_gradingrule_studentresult'),
        ('multitenancy', '0004_tenant_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='published_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='published_exams',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name='ClassTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'school_class',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='class_teachers',
                        to='academics.schoolclass',
                    ),
                ),
                (
                    'section',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='class_teachers',
                        to='academics.section',
                    ),
                ),
                (
                    'teacher',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='class_teacher_roles',
                        to='academics.teacher',
                    ),
                ),
                (
                    'tenant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='class_teachers',
                        to='multitenancy.tenant',
                    ),
                ),
            ],
            options={
                'unique_together': {('tenant', 'school_class', 'section')},
            },
        ),
    ]
