# Generated by Django 5.0.6 on 2026-02-11 18:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('academics', '0004_student_parent_contact'),
        ('academics', '0005_exam_published_at_exam_published_by_classteacher'),
    ]

    operations = []
