# Generated by Django 5.0.6 on 2026-02-11 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("multitenancy", "0004_tenant_features"),
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schools",
                to="multitenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="school",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="school",
            name="address",
            field=models.TextField(blank=True),
        ),
    ]
