# Generated by Django 5.0.6 on 2026-01-09 20:17

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('djstripe', '0012_2_8'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djstripe.price',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djstripe.product',),
        ),
    ]
