# Generated by Django 5.0.6 on 2026-01-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('multitenancy', '0002_alter_tenant_billing_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantmembership',
            name='invitee_email_address',
            field=models.EmailField(max_length=255),
        ),
    ]
