# Generated by Django 5.0.6 on 2026-01-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('multitenancy', '0003_alter_tenantmembership_invitee_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='features',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
