# Generated by Django 5.0.6 on 2026-01-09 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('academics', '0004_gradingrule_studentresult'),
        ('multitenancy', '0004_tenant_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'school_class',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='attendance_sessions',
                        to='academics.schoolclass',
                    ),
                ),
                (
                    'section',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='attendance_sessions',
                        to='academics.section',
                    ),
                ),
                (
                    'teacher',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='attendance_sessions',
                        to='academics.teacher',
                    ),
                ),
                (
                    'tenant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='attendance_sessions',
                        to='multitenancy.tenant',
                    ),
                ),
            ],
            options={
                'unique_together': {('tenant', 'date', 'school_class', 'section')},
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=True)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                (
                    'session',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='records',
                        to='attendance.attendancesession',
                    ),
                ),
                (
                    'student',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='attendance_records',
                        to='academics.student',
                    ),
                ),
            ],
            options={
                'unique_together': {('session', 'student')},
            },
        ),
    ]
