# Generated by Django 5.0.6 on 2026-01-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='status',
            field=models.CharField(
                choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20
            ),
        ),
    ]
